enum UserRole {
    admin
    organizer
    attendee
}

enum TicketStatus {
    confirmed
    cancelled
}

type Category {
    id: Int!
    name: String!
}

type User {
    id: Int!
    username: String!
    email: String!
    role: UserRole!
    createdAt: String!
    followerCount: Int
}

type TicketTier {
    id: Int!
    name: String!
    price: Float!
    capacity: Int!
    sold: Int!
}

type Event {
    id: Int!
    title: String!
    description: String!
    date: String!
    location: String!
    capacity: Int!
    ticketsLeft: Int!
    tiers: [TicketTier!]!
    category: Category!
    organizer: User!
    createdAt: String!
}

type Ticket {
    id: Int!
    event: Event!
    tier: TicketTier!
    seat: String
    purchasedAt: String!
    status: TicketStatus!
}


type Follow {
    id: Int!
    organizer: User!
    follower: User!
    createdAt: String!
}

type Query {
    events(category: String, date: String): [Event!]!
    event(id: Int!): Event!
    myTickets: [Ticket!]!

    myFollowedOrganizers: [User!]!
    organizerFollowers(organizerId: Int!): [User!]!
}

type Mutation {
    followOrganizer(organizerId: Int!): Follow!
    unfollowOrganizer(organizerId: Int!): Boolean!
}
